add passport NFC reader example
doo/scanbot-sdk-example-react-native pull request #25
Opened 2021-01-07 09:37 UTC by Superkachenya

2021-02-10 08:37 UTC, MrDyro requested changes
Update version of the SDK

2021-02-10 08:37 UTC, MrDyro commented on package.json
> +    "react-native-scanbot-sdk": "4.5.0-dev6",
Update to version 4.6.0 after the SDK is published

2021-02-15 17:01 UTC, MrDyro approved these changes
After the release of SDK v4.6.0 change the dependency here and merge it to master.

2021-02-15 17:01 UTC, MrDyro commented on package.json
> +    "react-native-scanbot-sdk": "4.6.0-beta1",
Change to 4.6.0 after the SDK was published.

2021-02-15 18:03 UTC, eddyfrank approved these changes

2021-02-15 18:03 UTC, merged